version: '3.9'

services:
  app:
    build: docker/app
    volumes:
      - ./:/usr/src
      - node-modules-volume:/usr/src/node_modules
    tty: true
    ports:
      - 8804:8000

  server:
    build: docker/server
    tty: true
    ports:
      - 8805:8000
    command: uvicorn main:app --port 8000 --host 0.0.0.0 --reload
    volumes:
      - ./docker/server/:/usr/src
    environment:
      - PYTHONDONTWRITEBYTECODE=1

volumes:
  node-modules-volume:
